### ISSUE TITLE
Graphics issues with integrated GPU

### ISSUE THREAD

**Issue by ABZB** [Dennis6492/KSP-RAM-Saver#1]
I am running this on a Lenovo laptop.
The listed GPU is "Intel(R) HD Graphics 4000" - I _think_ it is not a separate card.
Anyway, when I run it in auto mode, or use the OpenGL option - everything is amazing, except that aerodynamics effects are disabled (in options, the game claims that that feature is not supported by the hardware).

When I choose DirectX 11, the aerodynamics FX are present, but there are many terrain glitches - textures don't seem to load properly, the sea is monochrome grey, and the land is full of blank black patches,

**Comment by Dennis6492** [comment]
Intel(R) HD Graphics 4000 are integrated graphics, it is not a separate GPU, it depends on your CPU, and it has some constraints.Try to go on DirectX 9 mode, and see if you can have aerodynamics

**Comment by ABZB** [comment]
When I use DirectX 9, my game crashes (memory issue, it seems.) I will try with some stuff removed to see if it works...

With directX 11, the game loads, but I have terrain issues - the land featureless black, and the ocean is a uniform teal.

[I pushed the close button by accident while posting the above]

**Comment by Dennis6492** [comment]
Don't worry, how many mod do you have?, What's the size of your GameData folder?

**Comment by ABZB** [comment]
GameData is 1.71 GB
List of dlls loaded:
Mod DLLs found:
  Assembly-CSharp v1.0.0.0
  ModuleManager.2.5.1 v2.5.1.0
  aaa_Toolbar v1.0.0.0
  DynamicTanks v1.0.0.0
  USITools v1.0.0.0
  USI_Converter v1.0.0.0
  MiniAVC v1.0.2.3
  ActiveTextureManagement v1.0.0.0
  AdaptiveDockingNode v1.5.5311.28823
  CritterCrawler v0.0.0.0
  BDAnimationModules v0.0.0.0
  BetterTimeWarp v1.0.0.0
  AnchoredDecouplerFix v1.0.0.0
  EVAEjectionFix v1.0.0.0
  LargeCraftLaunchFix v1.0.0.0
  SymmetryActionFix v1.0.0.0
  DeadlyReentry v6.1.5401.38651
  DefaultThrottle v1.0.0.0
  EditorExtensions v1.4.5393.40222
  EVAParachutes v0.0.0.0
  ExsurgentEngineering v1.0.5122.3109
  KSPAPIExtensions v1.7.1.2
  Launchpad v4.4.0.0
  LaunchpadToolbar v4.2.3.0
  FerramAerospaceResearch v0.14.4.0
  ferramGraph v1.3.0.0
  Scale_Redist v1.0.0.0
  FinePrint v0.59.0.0
  Firespitter v7.0.5398.27328
  HlTest v1.0.0.0
  KAS v1.0.5394.34415
  KerbalFlightData v1.0.0.0
  Wheels v1.0.0.0
  KerbalIspDifficultyScaler v1.4.1.0
  KerbalJointReinforcement v2.4.4.0
  KineTechAnimation v1.0.0.0
  KSP-AVC v1.1.5.0
  LitJson v0.7.0.0
  InfernalRobotics v0.19.0.0
  MechJeb2 v2.3.0.0
  MechJebFARExt v1.0.0.0
  ModuleRCSFX v0.3.5393.39617
  DockingPortAlignment v1.0.0.0
  ModuleDockingNodeNamed v1.0.0.0
  NyanCat v1.0.5440.29685
  OpenResourceSystem_1_2_0 v1.1.0.0
  OpenResourceSystem_1_3_0 v1.1.0.0
  OpenResourceSystem_1_4_1 v1.1.0.0
  OpenResourceSystem_1_4_2 v1.4.2.0
  ORSX v1.0.0.0
  PadLock v1.0.0.0
  DeepFreeze v1.0.0.0
  PartHighlighter v1.0.0.0
  ResourceRecovery v1.0.0.0
  PreciseNode v1.0.0.0
  ProceduralFairings v0.0.0.0
  ProceduralParts v0.9.20.0
  QuantumStrutsContinued v1.1.5370.26424
  RCSBuildAid v0.5.2.15701
  RCSBuildAidToolbar v0.5.2.15702
  RealChute v1.2.5433.29228
  RealFuels v0.8.1.33418
  RealSolarSystem v0.8.2.1
  Regolith v1.0.0.0
  RemoteTech v1.0.0.0
  SafeChute v1.0.5438.42321
  SaneStrategies v1.0.0.0
  ScienceAlert v1.7.2.0
  SmokeScreen v2.5.0.0
  StageRecovery v1.5.1.0
  SwitchVessel v0.0.0.0
  TacFuelBalancer v2.4.1.0
  TarsierSpaceTech v4.5.5418.23135
  TechManager v1.4.0.0
  ModuleDB v1.0.5311.28823
  ToadicusTools v0.0.0.0
  KerbalAlarmClock v3.0.5.0
  KSPAlternateResourcePanel v2.6.0.0
  TweakableAnimateGeneric v1.5.5405.25485
  TweakableDecouplers v1.5.5405.25482
  TweakableDockingNode v1.5.5405.25482
  TweakableEngineFairings v1.5.5405.25485
  TweakableGimbals v1.5.5405.25484
  TweakableIntakes v1.5.5405.25487
  TweakableRCS v1.5.5405.25484
  TweakableReactionWheels v1.5.5405.25483
  TweakableSolarPanels v1.5.5405.25483
  TweakableStaging v1.5.5405.25481
  Scale v1.45.0.0
  Scale_Editor v1.0.0.0
  TweakScale_RealFuels v0.0.0.0
  UbioWeldingLtd v1.0.1.4
  Karbonite v1.0.0.0
  KarbPlus v1.0.0.0
  WarpEngine v1.0.0.0
  FrementGUILib v1.0.0.0
  VanguardTechnologies v0.7.5112.36481
  Interstellar v1.0.0.0
  InterstellarToolbar v1.0.0.0

**Comment by Dennis6492** [comment]
I recommend you use OpenGL mode, but if you want AerodynamicFX delete some mods and run the game as usual. Or buy a graphics card if you are able.
